```{r}
library(mixOmics)
library(pROC)
library(dplyr)
library(tidyverse)
quietroc=quietly(roc)
data.path="~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive"
data.file="LC pos Features CV0.3 SN3 INT10000 13spicy vs 20unspicy"
data= read.csv(paste(data.path,"/",data.file,"/",data.file,".csv",sep=""))
data$group=as.factor(data[,2])
permutation=1000
load(paste("~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive/LC pos Features CV0.3 SN3 INT10000 13spicy vs 20unspicy/ranking method ttest class method plsda ",permutation," iterations with 1408 compounds spicy.rda",sep=""))
```

```{r}
auc=result[[1]]
sum.vip=rep(0,nrow(auc))
for (i in 2:length(result)){
  tem.vip=result[[i]]
  tem.vip<-arrange(tem.vip,tem.vip$features)
  sum.vip<-sum.vip+tem.vip[,2]
}
ave.vip=data.frame()
ave.vip[1:nrow(auc),1]=tem.vip$features
ave.vip[1:nrow(auc),2]=sum.vip/1000
ave.vip<-arrange(ave.vip,desc(ave.vip$V2))
ave.vip.top=ave.vip[1:which.max(apply(result[[1]],1,mean)),]#max.ind
data.top=data[,colnames(data) %in% c(ave.vip.top$V1)]
data.top=cbind(data[,1:2],data.top)
```

```{r}
topdata=data[,colnames(data)%in%ave.vip.top$V1]
topdata=cbind(data[,1:2],topdata)
cv<-function(topdata){
round.n=data.frame()
round=list()
sample.list=data.frame()
im.total=data.frame()
im.total[1,1]=NA
for (samp in 2:(ncol(topdata)-2)){
  for (i in 1:1000){
    samples=sample((3:ncol(topdata)), samp, replace = FALSE)
    topdata.new=topdata[,samples]
    model.topn.new<-plsda(topdata.new,topdata[1:nrow(topdata),2],ncomp=2)
    predict.model.new<-predict(model.topn.new,newdata=topdata.new)
    #prob.bin.new=as.numeric(predict.model.new)
    prob.bin.new=as.numeric(predict.model.new$class$mahalanobis.dist[,2])
    roc.model.new<-quietroc(topdata[,2],prob.bin.new)
    im.total.new=as.numeric(roc.model.new[["result"]][["auc"]])
    if (im.total.new>0.8){
      sample.list[1:samp,ncol(sample.list)+1]=colnames(topdata[,samples])
    }
    round.n[i,1:2]=rbind(im.total.new,sum(samples))
  }
  round[[samp-1]]=round.n
  topndata=data[,colnames(data)%in%ave.vip.top$V1[1:samp]]
  model.topn<-plsda(topndata,topdata[1:nrow(topdata),2],ncomp=2)
  predict.model<-predict(model.topn,newdata=topndata)
  #prob.bin=as.numeric(predict.model.new)
  prob.bin=as.numeric(predict.model$class$mahalanobis.dist[,2])
  roc.model<-quietroc(topdata[,2],prob.bin)
  im.total.n=as.numeric(roc.model[["result"]][["auc"]])
  im.total[samp,1]=im.total.n
  print(paste("calculating ", samp," variables",sep=""))
}
round.list=list(im.total,round)
return(round.list)
#return(sample.list)
}
```


```{r}
plot.cv<-function(topn.im.total,cv.data){
library(ggplot2)
library(ggpmisc)
library(ggpp)
size=15
ggplot(cv.data, aes(V2, V1)) +
geom_point(color = "grey50",size = 3)+
geom_smooth(formula = y ~ x,method = lm)+
stat_poly_eq(aes(label = paste(..eq.label.., ..adj.rr.label.., sep = '~~~~')),formula = y ~ x,  parse = TRUE,size = 6,label.x = 0.1,label.y = 0.05)+
geom_line(aes(y=topn.im.total),linetype="dashed",colour="red",size=1)+
theme_classic()+
theme(
  axis.text.x = element_text(face="bold", color="#000000", size=size, angle=0,vjust=0.5),
  axis.text.y = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.x = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.y = element_text(face="bold", color="#000000", size=size, angle=90),
  legend.title = element_text(face="bold", color="#000000", size=size),
  legend.text = element_text(face="bold", color="#000000", size=size),
  legend.position="top")+
  labs(x ="Sum of the ranking number", y = "Area under curve(AUC)")
# plot(y[["V2"]],y[["V1"]])
# model<-lm(y[["V2"]]~y[["V1"]])
# abline(lm(V1~V2,data=y))
}
```


```{r}
data.plot=cv(topdata)
for (n in 2:(ncol(topdata)-2)){
file.name=paste("auc-",n," variables-1000 iterations",sep="")
cv.figure=plot.cv(data.plot[[1]][n,1],data.plot[[2]][[n-1]])
ggsave(paste(file.name,".regression.jpg",sep=""), plot = cv.figure,width = 5,height = 4)
}
```

遍历算法
```{r}
rand.list=list()
rand.sum=0
rand.ave=data.frame()
#rand=as.data.frame(combn(1:18,5))
for (i in 5){
  #time=ncol(rand)/2000
  for (j in 1:ncol(rand)){
    #rand<-sample(3:60,i,replace=FALSE)
    data.rand=cbind(data.top[,1:2],data.top[,rand[1:5,j]+2])
    #data.rand=cbind(data.top[,1:2],data.top[,rand])
    model.topn.rand<-plsda(data.rand[1:nrow(data.rand),3:ncol(data.rand)],data.rand[1:nrow(data.rand),2],ncomp=2)
    predict.model.rand<-predict(model.topn.rand,newdata=data.rand[1:nrow(data.rand),3:ncol(data.rand)])
    prob.bin.rand=as.numeric(predict.model.rand$class$mahalanobis.dist[,2])
    #prob.bin.rand=as.numeric(unlist(predict.model.rand))
    #prob.bin.rand=as.numeric(predict.model.rand)
    roc.model.rand<-quietroc(data.rand[,2],prob.bin.rand)
    im.total.rand=as.numeric(roc.model.rand[["result"]][["auc"]])
    rand[i+1,j]=im.total.rand
    print(paste("running on ",j," rands of subset",sep=""))
    #rand.sum=im.total.rand+rand.sum
  }
  #rand.list[[i]]=rand
  # rand.ave[i-1,1]=rand.sum/10000
  # rand=data.frame()
  # rand.sum=0
}
rand=t(rand)
#write.csv(rand4,"rand4.csv")
```

```{r}
draw.all<-data.frame()
draw.all[1:nrow(rand),1]<-apply(rand[,1:5],1,sum)
draw.all[1:nrow(rand),2]<-rand[,6]
library(ggplot2)
library(ggpmisc)
library(ggpp)
library(dplyr)
size=15
p=ggplot(draw.all, aes(V1, V2)) +
geom_point(color = "grey50",size = 3)+
geom_point(data=filter(draw.all,V2==max(draw.all$V2)),aes(V1, V2),color = "red",size = 3)+
geom_smooth(formula = y ~ x,method = lm)+
stat_poly_eq(aes(label = paste(..eq.label.., ..adj.rr.label.., sep = '~~~~')),formula = y ~ x,  parse = TRUE,size = 6,label.x = 0.1,label.y = 0.05)+
theme_classic()+
theme(
  axis.text.x = element_text(face="bold", color="#000000", size=size, angle=0,vjust=0.5),
  axis.text.y = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.x = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.y = element_text(face="bold", color="#000000", size=size, angle=90),
  legend.title = element_text(face="bold", color="#000000", size=size),
  legend.text = element_text(face="bold", color="#000000", size=size),
  legend.position="top")+
  labs(x ="Sum of the ranking number", y = "Area under curve(AUC)")

ggsave("5 features all.regression.jpg", plot =p,width = 6,height = 4)
```

