```{r}
library(mixOmics)
library(dplyr)
file.name="~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive/LC pos Features CV0.3 SN3 INT10000 22younger vs 42older/22younger vs 42older_1_5-18"
data= read.csv(paste(file.name,".csv",sep=""))
data=arrange(data,data$group)#very important because predict order is according to alphabet
group=unique(data$group)
label=as.numeric(data$group==group[2])+1
data$group=label
```

```{r}
#output performance of iteration
library(dplyr)
library(tidyverse)
library(pROC)
library(mixOmics)
spe.sen.performance<-function(data_,iteration_number){
performance=data.frame()
#divede into train and test group
  for (iteration in 1:iteration_number){
    data1=data_[data_$group==1,]
    data2=data_[data_$group==2,]
    #set.seed(100)
    ind1<-sample(nrow(data1),0.7*nrow(data1),replace=FALSE)
    ind2<-sample(nrow(data2),0.7*nrow(data2),replace=FALSE)
    train<-rbind(data1[ind1,],data2[ind2,])
    test<-rbind(data1[-ind1,],data2[-ind2,])
#build plsda model by train data
    plsda.model.train<-plsda(train[,3:ncol(train)],train[,2],ncomp=2)
#predict result by train data    
    predict.model.train<-predict(plsda.model.train,newdata=test[,3:ncol(test)],ncomp=2)
    prob.bin<-as.numeric(predict.model.train$class$mahalanobis.dist[,2])
    spe=sum(test[,2] !=1 & prob.bin !=1)/sum(test[,2]!=1)
    sen=sum(test[,2]==1 & prob.bin==1)/sum(test[,2]==1)
    performance[iteration,1]=spe
    performance[iteration,2]=sen
  }
  return(performance)
}
```

```{r}
true.performance=spe.sen.performance(data,1000)

true.performance[true.performance[,1]<=1 & true.performance[,1]>=0.9,3]=0.9
true.performance[true.performance[,1]<0.9 & true.performance[,1]>=0.8,3]=0.8
true.performance[true.performance[,1]<0.8 & true.performance[,1]>=0.7,3]=0.7
#draw.performance.true=cbind(true.performance,paste(true.performance$V1,"true"),"true")
#names(draw.performance.true)=c("spe","sen","speg","grp","col")
true.df=data.frame(spe=c(0.7,0.8,0.9),
                   mean=c(mean(true.performance[true.performance[,3]==0.7,2],na.rm=T),
                          mean(true.performance[true.performance[,3]==0.8,2],na.rm=T),
                          mean(true.performance[true.performance[,3]==0.9,2],na.rm=T)),
                   sd=c(sd(true.performance[true.performance[,3]==0.7,2],na.rm=T)/sqrt(sum(true.performance[,3]==0.7,na.rm=T)),
                        sd(true.performance[true.performance[,3]==0.8,2],na.rm=T)/sqrt(sum(true.performance[,3]==0.8,na.rm=T)),
                        sd(true.performance[true.performance[,3]==0.9,2],na.rm=T)/sqrt(sum(true.performance[,3]==0.9,na.rm=T))),
                   grp=c("true","true","true"))
                
group=unique(data$group)
ngroup=nrow(data)
ngroup1=sum(data$group==group[1])
ngroup2=sum(data$group==group[2])
ind<-sample(2,nrow(data),replace=TRUE,prob=c(ngroup1/ngroup,1-ngroup1/ngroup))
data_=data
data_[ind==1,2]<-1
data_[ind==2,2]<-2

false.performance=spe.sen.performance(data_,1000)
# false.performance[false.performance[,1]==0,3]=0
# false.performance[false.performance[,1]<0.5 & false.performance[,1]>0,3]=0.33
# false.performance[false.performance[,1]<0.7 & false.performance[,1]>0.5,3]=0.67
# false.performance[false.performance[,1]>0.7,3]=1
false.performance[false.performance[,1]<=1 & false.performance[,1]>=0.9,3]=0.9
false.performance[false.performance[,1]<0.9 & false.performance[,1]>=0.8,3]=0.8
false.performance[false.performance[,1]<0.8 & false.performance[,1]>=0.7,3]=0.7
draw.performance.false=cbind(false.performance,paste(false.performance$V1,"false"),"false")
#names(draw.performance.false)=c("spe","sen","speg","grp","col")
false.df=data.frame(spe=c(0.7,0.8,0.9),
                   mean=c(mean(false.performance[false.performance[,3]==0.7,2],na.rm=T),
                          mean(false.performance[false.performance[,3]==0.8,2],na.rm=T),
                          mean(false.performance[false.performance[,3]==0.9,2],na.rm=T)),
                   sd=c(sd(false.performance[false.performance[,3]==0.7,2],na.rm=T)/sqrt(sum(false.performance[,3]==0.7,na.rm=T)),
                        sd(false.performance[false.performance[,3]==0.8,2],na.rm=T)/sqrt(sum(false.performance[,3]==0.8,na.rm=T)),
                        sd(false.performance[false.performance[,3]==0.9,2],na.rm=T)/sqrt(sum(false.performance[,3]==0.9,na.rm=T))),
                   grp=c("false","false","false"))
draw.performance=rbind(true.df,false.df)
```


```{r}
library(ggplot2)
p=ggplot(draw.performance, aes(x=1-spe, y=mean, group=grp,color=grp)) +
  geom_point()+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.03)+
  geom_segment(aes(x = 1-draw.performance[4,1], y = draw.performance[4,2], xend = 1-draw.performance[5,1], yend = draw.performance[5,2]))+
  geom_segment(aes(x = 1-draw.performance[6,1], y = draw.performance[6,2], xend = 1-draw.performance[5,1], yend = draw.performance[5,2]))+
  geom_segment(aes(x = 1-draw.performance[3,1], y = draw.performance[3,2], xend = 1-draw.performance[2,1], yend = draw.performance[2,2]),color="lightblue")+
  geom_segment(aes(x = 1-draw.performance[2,1], y = draw.performance[2,2], xend = 1-draw.performance[1,1], yend = draw.performance[1,2]),color="lightblue")+
  scale_color_discrete(name = "Group", 
                       labels = c("Random", 
                                  "True")) +
  labs(y = "Sensitivity (True positive)",x="1-Specificity (False positive)") +
    theme(plot.title = element_text(color="black",size=15),
          axis.title.x=element_text(size=15),
          axis.title.y=element_text(size=15),
          panel.background = element_rect(fill = "white", colour="grey50"),
          axis.text=element_text(size=12),
          legend.title = element_text(colour="black", size=12),
          legend.text = element_text(colour="black", size=12),
          legend.position="top")
p
```
```{r}
ggsave("22younger vs 42older known age Internal validation_1_5-18.png", plot = p,width = 5,height = 4)
```

