```{r}
library(dplyr)
library(tidyverse)
```

Ranking variable by AUC value
```{r}
roc.rank<-function(train){
library(pROC)
auc.rank=data.frame()
for (i in 2:ncol(train)){
roc.model<- quietroc(train$group, train[,i])
auc.rank[i-1,1]=colnames(train)[i]
auc.rank[i-1,2]=as.numeric(roc.model[["result"]][["auc"]])
colnames(auc.rank)=c("features","auc")
}##注意control 和 case区分
return(auc.rank)
}
```

Ranking variable by VIP of top 1 components in PLSDA
```{r}
plsda.rank<-function(train){
library(mixOmics)
plsda.model<-plsda(train[1:nrow(train),2:ncol(train)],train[1:nrow(train),1],ncomp=2)
vip.12=as.data.frame(vip(pls(train[1:nrow(train),2:ncol(train)],as.numeric(train[1:nrow(train),1]))))
vip.rank=data.frame()
vip.rank[1:ncol(train),1]=colnames(train)
vip.rank[2:ncol(train),2]=sqrt((vip.12[,1])^2+(vip.12[,2])^2)
vip.rank=vip.rank[-1,]
colnames(vip.rank)=c("features","vip")
#plotIndiv(plsda.model, ind.names = FALSE, legend = TRUE, ellipse = TRUE,title = 'PLS-DA')
return(vip.rank)
}
```


Ranking variable by p-value
```{r}
ttest.rank<-function(train){
group.train=unique(train[,1])
train1=train[train$group==group.train[1],]
train2=train[train$group==group.train[2],]

pvalue.rank=data.frame()
for (i in 2:ncol(train)){
  pvalue.rank[i-1,1]=colnames(train)[i]
  pvalue=t.test(train1[,i],train2[,i])
  pvalue.rank[i-1,2]=pvalue$p.value
}
colnames(pvalue.rank)=c("features","pvalue")
return(pvalue.rank)
}
```

Ranking variable by random forest gini index
```{r}
rf.rank<-function(train){
library(randomForest)
# #选取randomforest –mtry节点值，对应误差最小为2，一般可默认
# for (i in 3:ncol(train)){
#   mtry_fit<-randomForest(group~.,data=train,mtry=2)
#   err<-mean(mtry_fit$err.rate)
#   print(err)
# }
# #选择ntree值，ntree指定随机森林所包含的决策树数目，默认为500, 看图稳定在多少
# #https://www.cnblogs.com/nxld/p/6374945.html
rf.model<-randomForest(group~.,data=train,mtry=2,ntree=3000)
# plot(rf.model)
gini.rank=importance(rf.model)#calculate gini index
gini.rank<-rownames_to_column(as.data.frame(gini.rank), var = "features") 
#Gini.plot=varImpPlot(rf.model)#draw gini index ranking plot 
colnames(gini.rank)=c("features","gini")
return(gini.rank)
}
```

Ranking variable by liner SVM
```{r}
svm.rank<-function(train){
#library(e1071)
#svm.model1<-svm(group~.,data=train,kernel = "linear")
#https://rpubs.com/uky994/593668
library(caret)
library(kernlab)
svm.model<-train(group~.,data=train,method="svmLinear",preProcess=c("center","scale"))
svmimp.rank<-varImp(object=svm.model)$importance
svmimp.rank<-rownames_to_column(svmimp.rank, var = "features") 
svmimp.rank<-svmimp.rank[,-3]
colnames(svmimp.rank)=c("features","svmimp")
return(svmimp.rank)
}
```

predict test group using plsda model
```{r}
plsda.class<-function(topn,train,test,class_method){
if (class_method=="plsda"){
library(mixOmics)
model.topn<-plsda(train[topn$features],train[1:nrow(train),1],ncomp=2)
predict.model<-predict(model.topn,newdata=as.matrix(test[topn$features]))
prob.num1<-as.numeric(sqrt(predict.model$predict[,1,1]^2+predict.model$predict[,1,2]^2))
prob.num2<-as.numeric(sqrt(predict.model$predict[,2,1]^2+predict.model$predict[,2,2]^2))
prob.bin<-matrix(0,length(prob.num1),1)
prob.bin[prob.num1<prob.num2,]=1


}else if (class_method=="rf") {
library(randomForest)
data_=cbind(train$group,train[topn$features])
colnames(data_)[1]="group"
model.topn<-randomForest(group~.,data=data_,mtry=2,ntree=3000)
predict.model<-predict(model.topn,newdata=test[topn$features],type = "prob", prob = TRUE)
prob.bin=as.numeric(predict.model)
}

  if (sum(prob.bin)==0){
    im.total=0
  }else{
roc.model<-quietroc(test[,1],prob.bin)
im.total=as.numeric(roc.model[["result"]][["auc"]])
  }

return(im.total)
}
```

use rank to select variable
```{r}
library(progress)    
rank.cv<-function(data,rank_method,class_method,iteration_number,topn_number){
pb <- progress_bar$new(format = "(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]",
                       total = iteration_number,
                       complete = "=",   # Completion bar character
                       incomplete = "-", # Incomplete bar character
                       current = ">",    # Current bar character
                       clear = FALSE,    # If TRUE, clears the bar when finish
                       width = 100)      # Width of the progress bar
auc.list=data.frame()
rank.list=list()
iteration=1
while(iteration < iteration_number+1){
group=unique(data[,2])
data1=data[data$group==group[1],]
data2=data[data$group==group[2],]
#set.seed(100)
run=0
while (run==0){
  ind1<-sample(2,nrow(data1),replace=TRUE,prob=c(0.7,0.3))
  if (sum(ind1)==length(ind1)){
    run=0
  }else{
    run=1
  }
}
ind2<-sample(2,nrow(data2),replace=TRUE,prob=c(0.7,0.3))

train<-rbind(data1[ind1==1,],data2[ind2==1,])
train=train[,-1]

test<-rbind(data1[ind1==2,],data2[ind2==2,])
test=test[,-1]
#print("part 1 okay")
if (rank_method=="ttest"){
  rank=ttest.rank(train)
  rank<-arrange(rank,rank$pvalue)
  }else if (rank_method=="roc"){
  rank=roc.rank(train)
  rank<-arrange(rank,desc(rank$auc))
  }else if (rank_method=="plsda"){
  rank=plsda.rank(train)
  rank<-arrange(rank,desc(rank$vip)) 
  }else if (rank_method=="rf"){
  rank=rf.rank(train)
  rank<-arrange(rank,desc(rank$gini)) 
  #print("part 2 okay")
  }else if (rank_method=="svm"){
  rank=svm.rank(train)
  rank<-arrange(rank,desc(rank$svmimp))
  }

rank.list[[iteration]]=rank
auc.increase=data.frame()
for (i in 2:topn_number){
  #print(paste("part 3 okay",i))
  topn<-rank[1:i,1:ncol(rank)]
  auc.increase[i,1]=plsda.class(topn,train,test,class_method)
  #print(paste("Running on top",i,"feature(s)"))
}
auc.list[1:topn_number,iteration]=auc.increase
print(paste("Ranking method",rank_method,"Class method",class_method,iteration,"iteration(s)"))

iteration=iteration+1
pb$tick()
}

auc.list=list(auc.list=auc.list)
result=c(auc.list,rank.list)
}
```



```{r}
data.path="~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive"
data.folder="/LC pos Features CV0.3 SN3 INT10000 proof/"
data.file="LC pos Features CV0.3 SN3 INT10000 proof for cut-off"
data= read.csv(paste(data.path,"/",data.folder,"/",data.file,".csv",sep=""))
colnames(data)[2]=c("group")
#only for proof
#########################
proof=unique(sort(data[,2]))
data1=data
for (i in 1:length(proof)){
data=data1
data$group[data$group<=proof[i]]=0
data$group[data$group>proof[i]]=1
proof.performance=data.frame()
#########################
data$group=as.factor(data$group)
library(pROC)
quietroc=quietly(roc)
setwd(paste(data.path,"/",data.folder,sep=""))
result=rank.cv(data,"plsda","plsda",1,ncol(data)-2)
proof.performance[i,1]=max(result[[1]],na.rm=TRUE)
#save(result,file="ranking method plsda class method plsda 10 iterations with 1408 compounds.rda")
result=rank.cv(data,"ttest","plsda",1,ncol(data)-2)
proof.performance[i,2]=max(result[[1]],na.rm=TRUE)
#save(result,file="ranking method ttest class method plsda 10 iterations with 1408 compounds.rda")
result=rank.cv(data,"roc","plsda",1,ncol(data)-2)
proof.performance[i,3]=max(result[[1]],na.rm=TRUE)
#save(result,file="ranking method roc class method plsda 10 iterations with 1408 compounds.rda")
result=rank.cv(data,"rf","plsda",1,ncol(data)-2)
proof.performance[i,4]=max(result[[1]],na.rm=TRUE)
#save(result,file="ranking method rf class method plsda 10 iterations with 1408 compounds.rda")
# result=rank.cv(data,"svm","plsda",1,ncol(data)-2)
# proof.performance[i,5]=max(result[[1]],na.rm=TRUE)
#save(result,file="ranking method svm class method plsda 10 iterations with 1408 compounds.rda")
print(paste("when proof is",proof[i],",the auc are",proof.performance[i,],sep=" "))
}
# result=rank.cv(data,"plsda","rf",10,ncol(data)-2)
# save(result,file="ranking method plsda class method rf 10 iterations with 1408 compounds.rda")
# result=rank.cv(data,"ttest","rf",10,ncol(data)-2)
# save(result,file="ranking method ttest class method rf 10 iterations with 1408 compounds.rda")
# result=rank.cv(data,"roc","rf",10,ncol(data)-2)
# save(result,file="ranking method roc class method rf 10 iterations with 1408 compounds.rda")
# result=rank.cv(data,"rf","rf",10,ncol(data)-2)
# save(result,file="ranking method rf class method rf 10 iterations with 1408 compounds.rda")
# result=rank.cv(data,"svm","rf",10,ncol(data)-2)
# save(result,file="ranking method svm class method rf 10 iterations with 1408 compounds.rda")
```






```{r}
compare=data.frame()
compare.sum=as.data.frame(matrix(0,ncol(data)-3,2))
for (k in 1:1){
group=unique(data[,2])
data1=data[data$group==group[1],]
data2=data[data$group==group[2],]
ind1<-sample(2,nrow(data1),replace=TRUE,prob=c(0.7,0.3))
ind2<-sample(2,nrow(data2),replace=TRUE,prob=c(0.7,0.3))
test<-data#rbind(data1[ind1==2,],data2[ind2==2,])
for (i in 2:nrow(ave.vip)){
rank.plsda<-arrange(rank.plsda,desc(rank.plsda$vip))
test.old=test[,colnames(test)%in%rank.plsda$features[1:i]]
test.new=test[,colnames(test)%in%ave.vip$V1[1:i]]

model.topn.old<-plsda(test.old,test[1:nrow(test),2],ncomp=2)
model.topn.new<-plsda(test.new,test[1:nrow(test),2],ncomp=2)

predict.model.old<-predict(model.topn.old,newdata=test.old,type = "response")
prob.bin.old=as.data.frame(predict.model.old)
rownames(prob.bin.old)=rownames(test)
prob.bin.old=as.numeric(unlist(prob.bin.old))
roc.model.old<-quietroc(test[,2],prob.bin.old)
im.total.old=as.numeric(roc.model.old[["result"]][["auc"]])

predict.model.new<-predict(model.topn.new,newdata=test.new,type = "response")
prob.bin.new=as.data.frame(predict.model.new)
rownames(prob.bin.new)=rownames(test)
prob.bin.new=as.numeric(unlist(prob.bin.new))
roc.model.new<-quietroc(test[,2],prob.bin.new)
im.total.new=as.numeric(roc.model.new[["result"]][["auc"]])

compare[i,1]=im.total.old
compare[i,2]=im.total.new
}
compare=compare[-1,]
x=nrow(compare)
compare.sum[1:x,1]=compare.sum[1:x,1]+compare[1:x,1]
compare.sum[1:x,2]=compare.sum[1:x,2]+compare[1:x,2]
print(k)
}
```


```{r}
file.name="All samples performance according to the vip ranking"
jpeg(paste(file.name,".jpg",sep=""),width = 700, height = 480)
plot(1:679,compare.sum[,1]/1,type="l",xlab="compound#",ylab="AUC",main="All samples performance according to the vip ranking")
lines(1:679,compare.sum[,2]/1,type="l",xlab="compound#",ylab="AUC",col=2)
legend(x = "topright",          # Position
       legend = c("PLS-DA before MCCV", "PLS-DA after MCCV"),  # Legend texts
       lty = c(1, 1),           # Line types
       col = c(1, 2),           # Line colors
       lwd = 2) 

dev.off()
```




```{r}

data= read.csv("ms dial clean.csv")
data$group=as.factor(data$group)
file.name="ranking method plsda class method plsda 1000 iterations with 680 compounds"
load("ranking method plsda class method plsda 1000 iterations with 680 compounds.rda")
ind<-sample(1000,1000,replace=FALSE)
auc=result$auc.list
auc=auc[,ind]
ave=as.data.frame(rowMeans(auc,2))
ave=ave[-1,]
# jpeg(paste(file.name,".jpg",sep=""),width = 700, height = 480)
# plot(1:679,ave,type="l",xlab="compound#",ylab="AUC",main=file.name)
# dev.off()
max.ind=which.max(ave)

sum.vip=rep(0,nrow(auc))
for (i in 2:length(result)){
  tem.vip=result[[i]]
  tem.vip<-arrange(tem.vip,tem.vip$features)
  sum.vip<-sum.vip+tem.vip$vip
}
ave.vip=data.frame()
ave.vip[1:nrow(auc),1]=tem.vip$features
ave.vip[1:nrow(auc),2]=sum.vip/1000
ave.vip<-arrange(ave.vip,desc(ave.vip$V2))
ave.vip.top=ave.vip[1:max.ind,]#max.ind
data.top=data[,colnames(data) %in% c(ave.vip.top$V1)]
data.top=cbind(data[,1:2],data.top)
```

遍历算法
```{r}
rand.list=list()
rand.sum=0
rand.ave=data.frame()
#rand=as.data.frame(combn(1:58,5))
for (i in 5){
  #time=ncol(rand)/2000
  for (j in 1:nrow(rand)){
    #rand<-sample(3:60,i,replace=FALSE)
    data.rand=cbind(data.top[,1:2],data.top[,rand[1:i,j]+2])
    #data.rand=cbind(data.top[,1:2],data.top[,rand])
    model.topn.rand<-plsda(data.rand[1:nrow(data.rand),3:ncol(data.rand)],data.rand[1:nrow(data.rand),2],ncomp=2)
    predict.model.rand<-predict(model.topn.rand,newdata=data.rand[1:nrow(data.rand),3:ncol(data.rand)])
    #prob.bin.rand=as.numeric(predict.model.rand$class$mahalanobis.dist[,2])
    prob.bin.rand=as.numeric(unlist(predict.model.rand))
    roc.model.rand<-quietroc(data.rand[,2],prob.bin.rand)
    im.total.rand=as.numeric(roc.model.rand[["result"]][["auc"]])
    rand[i+1,j]=im.total.rand
    print(paste("running on ",j," rands of subset",sep=""))
    #rand.sum=im.total.rand+rand.sum
  }
  #rand.list[[i]]=rand
  # rand.ave[i-1,1]=rand.sum/10000
  # rand=data.frame()
  # rand.sum=0
}
rand=t(rand)
#write.csv(rand4,"rand4.csv")

```

```


