#This code will exclude the redundancy of selected candidates by determining the optimal subset size for biomarkers biomarker, which provides output 2 in Figure 1.
#Figure 2D, 2E, 3C, 3D, 4C are generated by this code.

```{r}
library(mixOmics)
library(pROC)
library(dplyr)
library(tidyverse)
quietroc=quietly(roc)
data.path="~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive"
data.folder="LC pos Features CV0.3 SN3 INT10000 13spicy vs 20unspicy"
data.file="LC pos Features CV0.3 SN3 INT10000 13spicy vs 20unspicy"
data= read.csv(paste(data.path,"/",data.folder,"/",data.file,".csv",sep=""))
data$group=as.factor(data[,2])
permutation=1000
load(paste(data.path,"/",data.folder,"/ranking method plsda class method plsda ",permutation," iterations with 1408 compounds spicy.rda",sep=""))
```

```{r}
auc=result[[1]]
sum.vip=rep(0,nrow(auc))
for (i in 2:length(result)){
  tem.vip=result[[i]]
  tem.vip<-arrange(tem.vip,tem.vip$features)
  sum.vip<-sum.vip+tem.vip[,2]
}
ave.vip=data.frame()
ave.vip[1:nrow(auc),1]=tem.vip$features
ave.vip[1:nrow(auc),2]=sum.vip/1000
ave.vip<-arrange(ave.vip,desc(ave.vip$V2))
ave.vip.top=ave.vip[1:which.max(apply(result[[1]],1,mean)),]#max.ind
```

```{r}
topdata=data[,as.factor(colnames(data))%in%as.factor(ave.vip.top$V1)]
loc=match(ave.vip.top$V1,colnames(topdata))
topdata=topdata[,loc]
topdata=cbind(data[,1:2],topdata)
cv<-function(topdata){
round.n=data.frame()
round=list()
sample.list=data.frame()
im.total=data.frame()
im.total[1,1]=NA
for (samp in 2:(ncol(topdata)-2)){
  for (i in 1:1000){
    samples=sample((3:ncol(topdata)), samp, replace = FALSE)
    topdata.new=topdata[,samples]
    model.topn.new<-plsda(topdata.new,topdata[1:nrow(topdata),2],ncomp=2)
    predict.model.new<-predict(model.topn.new,newdata=topdata.new)
    prob<-predict.model.new[["predict"]]
    prob.num1.new<-as.numeric(sqrt(predict.model.new$predict[,1,1]^2+predict.model.new$predict[,1,2]^2))
    prob.num2.new<-as.numeric(sqrt(predict.model.new$predict[,2,1]^2+predict.model.new$predict[,2,2]^2))
    prob.bin.new<-matrix(0,length(prob.num1.new),1)
    prob.bin.new[prob.num1.new<prob.num2.new,]=1
    roc.model.new<-quietroc(topdata[,2],prob.bin.new)
    im.total.new=as.numeric(roc.model.new[["result"]][["auc"]])
    #the below give better performance but to be consistant, we use above
    # prob.bin.new=as.numeric(predict.model.new$class$mahalanobis.dist[,2])
    # roc.model.new<-quietroc(topdata[,2],prob.bin.new)
    # im.total.new=as.numeric(roc.model.new[["result"]][["auc"]])
    #if you want to report the list
    # if (im.total.new>0.8){
    #   sample.list[1:samp,ncol(sample.list)+1]=colnames(topdata[,samples])
    # }
    round.n[i,1:2]=rbind(im.total.new,sum(samples-2))
  }
  round[[samp-1]]=round.n
  topndata=data[,colnames(data)%in%ave.vip.top$V1[1:samp]]
  model.topn<-plsda(topndata,topdata[1:nrow(topdata),2],ncomp=2)
  predict.model<-predict(model.topn,newdata=topndata)
  prob.num1<-as.numeric(sqrt(predict.model$predict[,1,1]^2+predict.model$predict[,1,2]^2))
  prob.num2<-as.numeric(sqrt(predict.model$predict[,2,1]^2+predict.model$predict[,2,2]^2))
  prob.bin<-matrix(0,length(prob.num1),1)
  prob.bin[prob.num1<prob.num2,]=1
  roc.model<-quietroc(topdata[,2],prob.bin)
  im.total.n=as.numeric(roc.model[["result"]][["auc"]])
  #the below give better performance but to be consistant, we use above
  # prob.bin=as.numeric(predict.model.new$class$mahalanobis.dist[,2])
  # roc.model<-quietroc(topdata[,2],prob.bin)
  # im.total.n=as.numeric(roc.model[["result"]][["auc"]])
  im.total[samp,1]=im.total.n
  print(paste("calculating ", samp," variables",sep=""))
}
round.list=list(im.total,round)
return(round.list)
#return(sample.list)
}
```


```{r}
plot.cv<-function(topn.im.total,cv.data){
library(ggplot2)
library(ggpmisc)
library(ggpp)
size=15
ggplot(cv.data, aes(V2, V1)) +
geom_point(color = "grey50",size = 3)+
geom_smooth(formula = y ~ x,method = lm)+
stat_poly_eq(aes(label = paste(..eq.label.., ..adj.rr.label.., sep = '~~~~')),formula = y ~ x,  parse = TRUE,size = 6,label.x = 0.1,label.y = 0.05)+
geom_line(aes(y=topn.im.total),linetype="dashed",colour="red",size=1)+
theme_classic()+
theme(
  axis.text.x = element_text(face="bold", color="#000000", size=size, angle=0,vjust=0.5),
  axis.text.y = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.x = element_text(face="bold", color="#000000", size=size, angle=0),
  axis.title.y = element_text(face="bold", color="#000000", size=size, angle=90),
  legend.title = element_text(face="bold", color="#000000", size=size),
  legend.text = element_text(face="bold", color="#000000", size=size),
  legend.position="top")+
  labs(x ="Sum of the ranking number", y = "Area under curve(AUC)")
# plot(y[["V2"]],y[["V1"]])
# model<-lm(y[["V2"]]~y[["V1"]])
# abline(lm(V1~V2,data=y))
}
```


```{r}
data.plot=cv(topdata)
# for (n in 2:(ncol(topdata)-2)){
# file.name=paste("auc-",n," variables-1000 iterations",sep="")
# cv.figure=plot.cv(data.plot[[1]][n,1],data.plot[[2]][[n-1]])
# ggsave(paste(file.name,".regression.jpg",sep=""), plot = cv.figure,width = 5,height = 4)
# }
```

```{r}
library(plotly)
library(ggplot2)
data.plot.s=data.frame()
data.plot.r=data.frame()
for (i in 1:length(data.plot[[2]])){
  data.plot.temp=cbind(data.plot[[2]][[i]],replicate(1000,i+1))
  colnames(data.plot.temp)=c("AUC","Sum of the ranking number","Feature number")
  data.plot.s=rbind(data.plot.s,data.plot.temp)
  data.plot.r[i,1]=i+1
  data.plot.r[i,2]=sum(1:(i+1))
  data.plot.r[i,3]=data.plot[[1]][i+1,1]
  data.plot.r[i,4]=mean(data.plot[[2]][[i]][,1])
  ttest=t.test(data.plot[[2]][[i]][,1],data.plot[[2]][[i+1]][,1])
  data.plot.r[i,5]=ttest[["p.value"]]
}
```


```{r}
my_palette <- colorRampPalette(c("blue", "yellow"))(17)
my_palette1<- sort(rep.int(my_palette,1000))
p1=plot_ly(x=data.plot.s$`Feature number`, y=data.plot.s$`Sum of the ranking number`, z=data.plot.s$`AUC`, type="scatter3d", mode="markers",color=my_palette1) %>%#
  layout(scene=list(
    xaxis = list(title = "Feature#"),
       yaxis = list(title = 'Sum of feature#'),
        zaxis = list(title = 'Area Under Curve(AUC)')))
p2=plot_ly(x=data.plot.s$`Feature number`,y=data.plot.s$`AUC`, type="box",color=my_palette1)%>%
add_markers(x=data.plot.r[,1],y=data.plot.r[,3], type="scatter",color="red",marker=list(color="red",size=10, line=list(color="red", width=0)), line=list(color="gray", width=1),name="Top m features")%>%
layout(xaxis = list(title = 'Feature#',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(1, 19)),
       yaxis = list(title = 'Area Under Curve(AUC)',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(0.52, 0.95)))
 
p3=plot_ly(x=data.plot.s$`Sum of the ranking number`[data.plot.s$`Feature number`==4],y=data.plot.s$`AUC`[data.plot.s$`Feature number`==15], type="scatter",marker=list(color="C97F89",size=10),name="The average of random m features")%>%#F5D363
layout(xaxis = list(title = 'Sum of feature#',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(9, 140)),
       yaxis = list(title = 'Area Under Curve(AUC)',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(0.59, 0.99)))
```

```{r}
p1
p2
p3

```

