```{r}
library(mixOmics)
library(pROC)
quietroc=quietly(roc)

data.path="~/OneDrive - The Ohio State University/Rui Xu-Research/Bourbon study II 2021S-/Data Archive"
data.folder="LC pos Features CV0.3 SN3 INT10000 proof/"
data.file="LC pos Features CV0.3 SN3 INT10000 proof for cut-off"
setwd(paste(data.path,"/",data.folder,sep=""))
data= read.csv(paste(data.path,"/",data.folder,"/",data.file,".csv",sep=""))
colnames(data)[2]=c("group")
proof=unique(sort(data[,2]))
proof.performance=data.frame()
for (i in 1:(length(proof)-1)){
data_=data
data_$group[data_$group<=proof[i]]=0
data_$group[data_$group>proof[i]]=1

data1=data_[data_$group==0,]
data2=data_[data_$group==1,]



data_$group=as.factor(data_$group)

model<-plsda(data_[,-(1:2)],data_[,2],ncomp=2)
predict.model<-predict(model,newdata=data_[,-(1:2)])
prob.num1<-as.numeric(sqrt(predict.model$predict[,1,1]^2+predict.model$predict[,1,2]^2))
prob.num2<-as.numeric(sqrt(predict.model$predict[,2,1]^2+predict.model$predict[,2,2]^2))
prob.bin<-matrix(0,length(prob.num1),1)
prob.bin[prob.num1<prob.num2,]=1
roc.model<-quietroc(data_[,2],prob.bin)
im.total=as.numeric(roc.model[["result"]][["auc"]])
proof.performance[i,1]=proof[i]
proof.performance[i,2]=im.total
}
```
#This code helps with the searching of the best cutoff for proofs of bourbon.
#Figure 4A is generated by this code.
```{r}

library(plotly)
p=plot_ly(x=proof.performance[,1],y=proof.performance[,2], type="scatter",marker=list(color="black",size=10),line=list(color="gray", width=1),name="The average of random m features")%>%#F5D363
layout(xaxis = list(title = 'Proof',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(79, 132)),
       yaxis = list(title = 'Area Under Curve(AUC)',
                    showgrid = F, 
                    showline = T,
                    mirror = "ticks",
                    linecolor = toRGB("gray"),
                    linewidth = 1,
                    range = c(0.48, 0.87)))
```

